export const courseData = {
  cs101: {
    name: "Computer Science 101",
    code: "CS101",
    instructor: "Dr. Sarah Johnson",
    schedule: "Mon, Wed, Fri - 9:00 AM - 10:30 AM",
    location: "Room A-204",
    attendance: 85,
    attendedClasses: 17,
    totalClasses: 20,
    nextSession: {
      date: "Tomorrow",
      time: "9:00 AM - 10:30 AM",
      location: "Room A-204",
    },
    recentAttendance: [
      {
        date: "Jan 15",
        status: "present" as const,
        time: "9:15 AM",
        verified: true,
        locationAccuracy: 98,
      },
      {
        date: "Jan 13",
        status: "present" as const,
        time: "9:10 AM",
        verified: true,
        locationAccuracy: 96,
      },
      {
        date: "Jan 11",
        status: "late" as const,
        time: "9:25 AM",
        verified: true,
        locationAccuracy: 94,
      },
      {
        date: "Jan 8",
        status: "present" as const,
        time: "9:12 AM",
        verified: true,
        locationAccuracy: 97,
      },
      {
        date: "Jan 6",
        status: "absent" as const,
        time: "-",
        verified: false,
        locationAccuracy: 0,
      },
    ],
  },
  math201: {
    name: "Mathematics 201",
    code: "MATH201",
    instructor: "Prof. Michael Chen",
    schedule: "Tue, Thu - 11:00 AM - 12:30 PM",
    location: "Room B-105",
    attendance: 72,
    attendedClasses: 13,
    totalClasses: 18,
    nextSession: {
      date: "Today",
      time: "11:00 AM - 12:30 PM",
      location: "Room B-105",
    },
    recentAttendance: [
      {
        date: "Jan 14",
        status: "present" as const,
        time: "11:10 AM",
        verified: true,
        locationAccuracy: 95,
      },
      {
        date: "Jan 12",
        status: "present" as const,
        time: "11:05 AM",
        verified: true,
        locationAccuracy: 99,
      },
      {
        date: "Jan 9",
        status: "absent" as const,
        time: "-",
        verified: false,
        locationAccuracy: 0,
      },
      {
        date: "Jan 7",
        status: "present" as const,
        time: "11:15 AM",
        verified: true,
        locationAccuracy: 93,
      },
      {
        date: "Jan 5",
        status: "partial" as const,
        time: "11:45 AM",
        verified: false,
        locationAccuracy: 0,
      },
    ],
  },
  phy301: {
    name: "Physics 301",
    code: "PHY301",
    instructor: "Dr. Emily Rodriguez",
    schedule: "Mon, Wed - 2:00 PM - 3:30 PM",
    location: "Lab C-301",
    attendance: 68,
    attendedClasses: 11,
    totalClasses: 16,
    nextSession: {
      date: "Today",
      time: "2:00 PM - 3:30 PM",
      location: "Lab C-301",
    },
    recentAttendance: [
      {
        date: "Jan 14",
        status: "absent" as const,
        time: "-",
        verified: false,
        locationAccuracy: 0,
      },
      {
        date: "Jan 12",
        status: "present" as const,
        time: "2:05 PM",
        verified: true,
        locationAccuracy: 92,
      },
      {
        date: "Jan 10",
        status: "absent" as const,
        time: "-",
        verified: false,
        locationAccuracy: 0,
      },
      {
        date: "Jan 8",
        status: "late" as const,
        time: "2:20 PM",
        verified: true,
        locationAccuracy: 89,
      },
      {
        date: "Jan 5",
        status: "present" as const,
        time: "2:10 PM",
        verified: true,
        locationAccuracy: 96,
      },
    ],
  },
}
